export const TruckListData = [
  {
    id: 1,
    name: "Icv Truck",
    capacity: "120Ton",
    amount: 700,
    image: "/icv-truck.jpg",
  },
  {
    id: 2,
    name: "Tata-signa",
    capacity: "150Ton",
    amount: 900,
    image: "/tata-signa-5530-truck.png",
  },
  {
    id: 3,
    name: "Pakistani Truck",
    capacity: "160Ton",
    amount: 500,
    image: "/Pakistani_truck.jpg",
  },
  {
    id: 4,
    name: "Full Pujab",
    capacity: "100Ton",
    amount: 800,
    image: "/full_punjab.jpg",
  },
  {
    id: 5,
    name: "Blazo X",
    capacity: "140Ton",
    amount: 1000,
    image: "/blazo-x-35.jpg",
  },
  {
    id: 6,
    name: "New Truck",
    capacity: "170Ton",
    amount: 1100,
    image: "/new_truck.jpg",
  },
  {
    id: 7,
    name: "Freightliner Truck",
    capacity: "155Ton",
    amount: 1200,
    image: "/Freightliner_truck.jpg",
  },
];
